In [1]:
import torch
import numpy as np

In [2]:
t1=torch.Tensor([1,2,3])
print(t1)

tensor([1., 2., 3.])


In [21]:
array1=np.arange(12).reshape(3,4)
t2=torch.Tensor(array1)
print(t2)
print(t2.shape)
print(t2.size(1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])
4


In [15]:
t2[0:1,]

tensor([[0., 1., 2., 3.]])

In [18]:
a=torch.tensor(np.arange(1))

print(a.item())

0


只能对标量tensor用item

In [34]:
t3=torch.tensor([[[3,4]]])
print(t3)
print(t3.shape)
print(t3.view([2]))
print(t3.view([1,2]))

tensor([[[3, 4]]])
torch.Size([1, 1, 2])
tensor([3, 4])
tensor([[3, 4]])


In [35]:
b=t3.view([2,-1])
print(b)

tensor([[3],
        [4]])


In [37]:
b[0,0]=100
print(b)
print(t3)

tensor([[100],
        [  4]])
tensor([[[100,   4]]])


两者共享地址，所以是浅copy

In [39]:
print(t3.dim())

3


In [41]:
t4=torch.tensor(np.arange(24).reshape(2,3,4))
print(t4.shape)
print(t4.permute(1,0,2))
print(t4.permute(1,0,2).shape)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])
torch.Size([3, 2, 4])


In [51]:
x = torch.tensor(np.arange(12).reshape(3, 4), dtype=torch.float32)
y=torch.ones([3,4])

x.sub_(y)
print(x)

tensor([[-1.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10.]])


这里不指定x的类型会报错

In [52]:
"""
GPU中tensor的使用:
1.实例化device. torch.device("cpu" or "cuda:0"),选cuda:0需要torch.cuda.is_available()==true
2.tensor.to(device),把tensor转化为CUDA支持的tensor或者CPU支持的tensor
"""
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda") #cuda device对象
    y = torch.ones_like(x, device = device) #创建一个在cuda上的tensor
    x = x.to(device) #把x转为cuda上的tensor
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

# torch.tensor([1.9806], device = "cuda:0")
device = torch.device("cpu")
x.to(device)

True
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], device='cuda:0')
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)


tensor([[-1.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10.]])

张量乘法是hadmard乘积

In [53]:
import torch
import numpy as np

# 1. 创建两个形状相同的张量 (3行4列)
# np.arange(12) 生成 0到11 的数字
# reshape(3, 4) 变成 3x4 矩阵
t8 = torch.tensor(np.arange(12).reshape(3,4), dtype=torch.float32)
t9 = torch.tensor(np.arange(12).reshape(3,4), dtype=torch.float32)

# 2. 元素对应相乘 (Element-wise Multiplication)
# 对应位置的数相乘，例如 [0,0]位置 * [0,0]位置
print(t8 * t9)
# 结果形状依然是 (3, 4)

# 3. 矩阵乘法 (Matrix Multiplication)
# torch.mm 是 Matrix Multiply 的缩写
# t8 的形状是 (3, 4)
# t9 的形状是 (3, 4)，这两个不能直接做矩阵乘法！
# 必须把 t9 转置 (transpose) 成 (4, 3)
# (3, 4) 乘以 (4, 3) -> 结果形状是 (3, 3)
print(torch.mm(t8, t9.transpose(0, 1)))

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])
tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])
