In [11]:
import numpy as np
import random
a=np.random.randint(0, 100, size=(6, 6))
a = a.astype(float)
a[3,4]=np.nan
a[5,5]=np.nan
print(a)
for i in range(a.shape[1]):
    temp_col=a[:,i]
    nan_num=np.count_nonzero((temp_col!=np.nan))
    if nan_num!=0:
          temp_col_not_nan = temp_col[temp_col == temp_col]
          temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print(a)



[[95. 22. 19. 10. 81. 15.]
 [55. 26. 70. 95. 65. 91.]
 [11. 16. 92. 43. 86. 67.]
 [48. 19. 10.  6. nan 54.]
 [21. 58.  3. 97. 19. 92.]
 [10.  0. 16. 48. 43. nan]]
[[95.  22.  19.  10.  81.  15. ]
 [55.  26.  70.  95.  65.  91. ]
 [11.  16.  92.  43.  86.  67. ]
 [48.  19.  10.   6.  58.8 54. ]
 [21.  58.   3.  97.  19.  92. ]
 [10.   0.  16.  48.  43.  63.8]]


In [12]:
print(type(np.nan+np.inf))

<class 'float'>


In [17]:
import numpy as np
a=np.arange(24).reshape(4,6)
print(a)
print(np.transpose(a))
a1=a.swapaxes(1,0)
print(a1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [18]:
b=np.arange(60).reshape(3,4,5)
print(b)
b1=b.swapaxes(1,2)
print(b1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]


In [20]:
import numpy as np
a=np.ones((3,4,5,6))
print(a)
print(np.rollaxis(a,3,1).shape)
#把轴3放到轴1的位置前面，其他轴依次后移

[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1

In [21]:
ran= np.random.rand(3,4,5)
print(ran)

[[[0.60320023 0.41722154 0.35719754 0.98097455 0.82077202]
  [0.91497776 0.10883107 0.45103544 0.63160641 0.92718716]
  [0.00907929 0.287223   0.40641073 0.55239652 0.98817516]
  [0.53728784 0.49616528 0.45326139 0.41896263 0.26833955]]

 [[0.28326215 0.63517698 0.98971914 0.27303104 0.17466286]
  [0.23328502 0.71852196 0.50640824 0.67658505 0.88630871]
  [0.71813788 0.2237235  0.76709211 0.92520359 0.46429128]
  [0.34389142 0.55555675 0.12640544 0.38909067 0.30275663]]

 [[0.13496384 0.48839445 0.90605703 0.17152248 0.94087973]
  [0.48497211 0.05992055 0.82140653 0.5313049  0.31649388]
  [0.79520095 0.83313054 0.56108535 0.31038359 0.60041701]
  [0.62482617 0.36581761 0.57691865 0.60566316 0.84295714]]]


In [26]:
names="Alice,Bob,Cathy,David"
#写入文件
with open("names.csv","w") as f:
    f.write(names)
    f.write("\n")
    f.write("12,23,34,45")